/* This file is part of the 'atomes' software

'atomes' is free software: you can redistribute it and/or modify it under the terms
of the GNU Affero General Public License as published by the Free Software Foundation,
either version 3 of the License, or (at your option) any later version.

'atomes' is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the GNU General Public License for more details.

You should have received a copy of the GNU Affero General Public License along with 'atomes'.
If not, see <https://www.gnu.org/licenses/>

Copyright (C) 2022-2026 by CNRS and University of Strasbourg */

/*
 * This file is generated by gdbus-codegen, do not modify it.
 *
 * The license of this code is the same as for the D-Bus interface description
 * it was derived from. Note that it links to GLib, so must comply with the
 * LGPL linking clauses.
 */

#ifndef __FR_IPCMS_ATOMES_INSTANCE_H__
#define __FR_IPCMS_ATOMES_INSTANCE_H__

#include <gio/gio.h>

G_BEGIN_DECLS


/* ------------------------------------------------------------------------ */
/* Declarations for fr.ipcms.atomes.Instance */

#define TYPE_INSTANCE (instance_get_type ())
#define INSTANCE(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_INSTANCE, Instance))
#define IS_INSTANCE(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_INSTANCE))
#define INSTANCE_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), TYPE_INSTANCE, InstanceIface))

struct _Instance;
typedef struct _Instance Instance;
typedef struct _InstanceIface InstanceIface;

struct _InstanceIface
{
  GTypeInterface parent_iface;

  gboolean (*handle_open_file) (
    Instance *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_atomes);

};

GType instance_get_type (void);

GDBusInterfaceInfo *instance_interface_info (void);
guint instance_override_properties (GObjectClass *klass, guint property_id_begin);


/* D-Bus method call completion functions: */
void instance_complete_open_file (
    Instance *object,
    GDBusMethodInvocation *invocation);



/* D-Bus method calls: */
void instance_call_open_file (
    Instance *proxy,
    const gchar *arg_atomes,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean instance_call_open_file_finish (
    Instance *proxy,
    GAsyncResult *res,
    GError **error);

gboolean instance_call_open_file_sync (
    Instance *proxy,
    const gchar *arg_atomes,
    GCancellable *cancellable,
    GError **error);



/* ---- */

#define TYPE_INSTANCE_PROXY (instance_proxy_get_type ())
#define INSTANCE_PROXY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_INSTANCE_PROXY, InstanceProxy))
#define INSTANCE_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), TYPE_INSTANCE_PROXY, InstanceProxyClass))
#define INSTANCE_PROXY_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), TYPE_INSTANCE_PROXY, InstanceProxyClass))
#define IS_INSTANCE_PROXY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_INSTANCE_PROXY))
#define IS_INSTANCE_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), TYPE_INSTANCE_PROXY))

typedef struct _InstanceProxy InstanceProxy;
typedef struct _InstanceProxyClass InstanceProxyClass;
typedef struct _InstanceProxyPrivate InstanceProxyPrivate;

struct _InstanceProxy
{
  /*< private >*/
  GDBusProxy parent_instance;
  InstanceProxyPrivate *priv;
};

struct _InstanceProxyClass
{
  GDBusProxyClass parent_class;
};

GType instance_proxy_get_type (void);

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (InstanceProxy, g_object_unref)
#endif

void instance_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
Instance *instance_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error);
Instance *instance_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);

void instance_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
Instance *instance_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error);
Instance *instance_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);


/* ---- */

#define TYPE_INSTANCE_SKELETON (instance_skeleton_get_type ())
#define INSTANCE_SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_INSTANCE_SKELETON, InstanceSkeleton))
#define INSTANCE_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), TYPE_INSTANCE_SKELETON, InstanceSkeletonClass))
#define INSTANCE_SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), TYPE_INSTANCE_SKELETON, InstanceSkeletonClass))
#define IS_INSTANCE_SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_INSTANCE_SKELETON))
#define IS_INSTANCE_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), TYPE_INSTANCE_SKELETON))

typedef struct _InstanceSkeleton InstanceSkeleton;
typedef struct _InstanceSkeletonClass InstanceSkeletonClass;
typedef struct _InstanceSkeletonPrivate InstanceSkeletonPrivate;

struct _InstanceSkeleton
{
  /*< private >*/
  GDBusInterfaceSkeleton parent_instance;
  InstanceSkeletonPrivate *priv;
};

struct _InstanceSkeletonClass
{
  GDBusInterfaceSkeletonClass parent_class;
};

GType instance_skeleton_get_type (void);

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (InstanceSkeleton, g_object_unref)
#endif

Instance *instance_skeleton_new (void);


G_END_DECLS

#endif /* __FR_IPCMS_ATOMES_INSTANCE_H__ */
