.TH MONCOMMANDE 1 "7 avril 2026" "Projet Exemple" "Commandes utilisateur"
.SH NOM
\fBmoncommande\fR \- Une commande exemple avec des options de base et spéciales.
.SH SYNOPSIS
\fBmoncommande\fR [\fI-OPTIONS_DE_BASE\fR] [\fI--OPTIONS_SPECIALES\fR...]
.SH DESCRIPTION
\fBmoncommande\fR est une commande exemple pour illustrer la structure d'une page de manuel.
.SH OPTIONS
Les options de base sont :
.TP
\fB\-h\fR, \fB\-\-help\fR
Affiche l'aide et quitte.
.TP
\fB\-v\fR, \fB\-\-version\fR
Affiche la version et quitte.
.TP
\fB\-f\fR \fIFICHIER\fR
Spécifie le fichier à traiter.
.SH OPTIONS SPÉCIALES
Les options spéciales sont :
.TP
\fB\-\-special1\fR=\fIVALEUR\fR
Active le mode spécial 1 avec une valeur.
.TP
\fB\-\-special2\fR
Active le mode spécial 2.
.SH EXEMPLES
Pour utiliser la commande :
.IP
\fBmoncommande \-f fichier.txt \-\-special1=valeur\fR
.SH AUTEUR
Écrit par Sébastien LE ROUX.
.SH BOGUES
Signalez les bugs sur <https://exemple.com/bugs>.
